### ISSUE TITLE
Hospital and Market inaccessible

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#113]
Placing the pin on this hospital, the Spaarne Gasthuis Haarlem-Noord, gives an accessibility result of zero: 
![image](https://cloud.githubusercontent.com/assets/112871/14293155/92b294a0-fb6b-11e5-9243-7236319ebee5.png)

There are roads tagged highway=service in that area:
http://www.openstreetmap.org/way/34909998

**Comment by abyrd** [comment]
Another example at Hoofddorp Marktplein:
![image](https://cloud.githubusercontent.com/assets/112871/14293578/791ea0b8-fb6d-11e5-81fe-6217f162d2e2.png)

Again, the marker happens to be right on a highway=service tagged OSM way:
http://www.openstreetmap.org/way/400576990

**Comment by abyrd** [comment]
This is affecting shapefile linking as well. Contrast:
![image](https://cloud.githubusercontent.com/assets/112871/14295452/f7aab888-fb75-11e5-9fe2-6d9cb6d0bf50.png)

with

![image](https://cloud.githubusercontent.com/assets/112871/14295465/093381e8-fb76-11e5-89ae-f8c33bff2101.png)

**Comment by buma** [comment]
That first is inaccessible is probably because service way is connected to [highway=primary with foot=no and bicycle=no](https://www.openstreetmap.org/way/7403432#map=18/52.42194/4.65018). and can't be walked/cycled to from anywhere. But can be driven to.

You can start the server (R5Main) with `point --graphs path do directory with network.dat` and use serverurl:8080/debug.html to see road permissions and flags if there is the same problem in other areas. Default permissions are in TraversalPermissionLabeler class. highway=service has access=yes (meaning all ways of transport allowed)

**Comment by abyrd** [comment]
Thanks @buma. I was aware of the permissions layer but happened to see this problem while working in Analyst on a remote server, so just wanted to document the problem until I could look at it locally.

**Comment by ansoncfit** [comment]
Common causes of this issue should be fixed with mode-specific island pruning code in https://github.com/conveyal/r5/pull/248 and the more selective linking in https://github.com/conveyal/r5/commit/d0f09943fb62d336987eb103b3cb7742984077c0

We still might see similar unexpected results due to #505, but I think this issue can be closed.
