### ISSUE TITLE
Cannot add stops to only some trips

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#134]
An add stops modification currently has to apply to an entire route, which isn't necessarily desirable.

**Comment by abyrd** [comment]
This was intentional, since if you modify some trips on a pattern and not others you create a new pattern. I think the last time we talked about this, we decided to keep it simple until we had a need to do otherwise.

I am starting to wonder though if we should (in the future) allow specifying routes and patterns to modify instead of routes and trips, with patterns specified as lists of stops. Not just in this modification, but in all of them. The UI side is all in terms of patterns and routes.

**Comment by abyrd** [comment]
@mattwigway I'm now noticing that the add-stops modifications coming out of the scenario editor have lists of trips. My understanding was that this modification type should only accept routes, because modifying certain trips and not others on a pattern will lead to incorrect results. On the other hand, I understand that we often need to reroute the patterns going in opposite directions on a particular route independently. On a route that reused the same stops in both directions, rerouting one end of the route would be impossible.

Generally speaking we need to come up with a solution for this. As mentioned above I'm leaning toward specifying which patterns to modify instead of which trips, but I'm curious to have your thoughts on this.

**Comment by abyrd** [comment]
Our solution is #144. We will list patterns to be modified using at least one example trip from each pattern, in a field called "patterns". The "trips" field will be unused until we have a good reason.
