### ISSUE TITLE
JARs are not deployed to r5-builds

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#190]
Since db386749e0d2308572625b31cf007bc0176d67ec, JARs are not being deployed to r5-builds. It appears that the git commit id plugin is being overridden, which makes the build work in IDEs but means that version properties are not passed in command-line/travis build.

**Comment by abyrd** [comment]
Here's the situation: we need to use the Git commit ID information in two different ways. First, we need to name the shaded Maven artifact using the Git describe string so we know what commit it corresponds to once it's copied to S3. Second, we need to get the information into the running code so R5 is aware of its own version and commit number. 

We get the commit information within Maven using https://github.com/ktoso/maven-git-commit-id-plugin. This plugin can set a Maven property or create a Java properties file during the build, but apparently not both at once. Since we absolutely need the Maven property to be set (so we can use it in the Shade plugin configuration in the POM to name the shaded artifact) we use that mode. We then produce the Java properties file (which will be read when R5 starts up to give it knowledge of its own version/commit) using Maven "resource filtering", where strings like `${variable.name}` are interpolated in resource files when they are copied to the target directory during a build.

This works fine, except that the Git commit ID plugin is not run by IDEA or other IDEs. I believe this is because the IDEA implements its own Maven build process that resolves dependencies and compiles code, only running certain specific phases of the Maven build or skipping over plugins that are not known to it. StackOverflow confirms that IntellJ does not use Maven to perform builds, it simply interprets the POM as instructions for its own build system. http://stackoverflow.com/a/5820003/778449

Still, perhaps there is some way to make sure the plugin runs before the compilation phase.

By default, the git-commit-id-plugin binds to the validate phase which happens right at the beginning of the build. For reference, the default Maven build lifecycle is:

```
validate
initialize
generate-sources
process-sources
generate-resources
process-resources
compile
...
test
package
install
deploy
```

IntelliJ does allow you to select build phases in its Maven Projects tool and set them to run before or after a project make, run, or rebuild. But not all phases are included, and the initialize phase is one of the missing ones.

Considering all this, we have just accepted that when working locally with R5, we won't have an accurate Git describe string and we'll instead just use UNKNOWN. This UNKNOWN value needs to make it into the shaded artifact name and the runtime version information. There seemed to be an obvious way to do this. We'd set the git.commit properties like so in the POM:

```
<properties>
    <git.commit.id>UNKNOWN</git.commit.id>
    <git.commit.id.describe>UNKNOWN</git.commit.id.describe>
  </properties>
```

The Git commit ID plugin would then overwrite them if it runs, and leave them UNKNOWN if it doesn't run. IntelliJ handles this "correctly" in that the Git commit ID plugin does not run, but the `${git.commit.id.describe}` strings in the resources are replaced with the default UNKNOWN string and make it through to the running R5. However, this doesn't work on command line builds. The Git commit plugin is run, but the Maven properties remain at their default value of UNKNOWN. The shaded JAR is named UNKNOWN.

One possible solution is to remove the default UNKNOWN values in the POM and programmatically check for uninterpolated values in the Java properties file (strings that start with `$`) replacing them with UNKNOWN.

**Comment by abyrd** [comment]
I have checked the docs and there doesn't seem to be any way to force the plugin to overwrite pre-set Maven properties (in this case `<git.commit.id>UNKNOWN</git.commit.id> <git.commit.id.describe>UNKNOWN</git.commit.id.describe>). Proceeding with active detection of uninterpolated strings in code.

**Comment by abyrd** [comment]
Appears to be fixed, with command line builds creating properly named artifacts and reporting the correct git describe on startup. IDE builds report UNKNOWN.
