### ISSUE TITLE
Allow schedule modifications in remove stops modification

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#237]
When removing stops in the middle of route (for instance, for stop consolidation reasons), we often want to remove the time associated with those stops. The remove-stops modification currently removes the dwell time, but a) that doesn't capture the additional time spent in acceleration and deceleration, and b) doesn't work at all on the many feeds that do not include dwell times.

We should add a removeSeconds field to the remove-stops modification which removes an additional _n_ seconds from the schedule where stops are removed, and throws an error when that leaves less than 1 second of travel time between stops.

We need this for some MassDOT modeling we're trying to complete next week. I'll take the lead on implementation.

**Comment by mattwigway** [comment]
@abyrd do you have any thoughts on this? If not I'll proceed with implementation next week.

**Comment by abyrd** [comment]
@mattwigway this makes perfect sense to me. I do wonder whether it should block application of the scenario entirely when removeSeconds leads to negative travel time, just because I've seen so many zero/small hop time problems throughout feeds, which people have then claimed were expected/normal. Alternatives are clamping to zero, or not subtracting out the seconds at all when it would lead to zero/negative travel times. But I don't think we'd want to do those things silently, so throwing an error is a good initial approach.

**Comment by mattwigway** [comment]
👍
