### ISSUE TITLE
Retain existing trips outside frequency entries in adjust frequency modification causes NPE in frequencyrandomoffsets

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#250]
We had an issue for this in Asana; turning on the "Retain existing trips outside frequency entries" checkbox in a convert-to-frequency modification causes R5 to crash, and I just ran into it again with MassDOT.

@abyrd I believe you were going to take a look at this?

**Comment by mattwigway** [comment]
This appears to be worse than previously thought, as it seems to also prevent worker shutdown.

**Comment by abyrd** [comment]
This appears to be caused by some code assuming that patterns contain either all frequency trips, or all scheduled trips, but not a mix of both. When the FrequencyRandomOffsets constructor encounters a mixed pattern (with both frequency and scheduled trips), it will still make an offsets array for that pattern, but some of the offsets will be null (indicating that particular trip on the pattern is not frequency-based). 

retainTripsOutsideFrequencyEntries will lead to mixed frequency / schedule patterns.
