### ISSUE TITLE
All Non walkable street are removed when islands are removed

### ISSUE THREAD

**Issue by buma** [conveyal/r5#27]
I was debugging missing motorways and found that since [removeDisconnectedSubgraph](https://github.com/conveyal/r5/blob/master/src/main/java/com/conveyal/r5/streets/StreetLayer.java#L381) uses streetRouter which uses WALK mode by default ever since permissions were added non walkable streets are removed. This is mostly motorways. When I build graph without removing islands motorways are back.

When I added support for permission in TN previously same thing happened. I added switchMode parameter to request which used any mode available during routing. [Commit](https://github.com/buma/OpenTripPlanner-Maribor/commit/d500365570367a08653d65c8ccd22a2f070b01f7) if this would be OK I can do the same here.

In OTP edges which are supposed to be prunned are first checked if they have traversable permissions and are removed only if they can't be walked or cycled. If I understand the [code](https://github.com/opentripplanner/OpenTripPlanner/blob/master/src/main/java/org/opentripplanner/common/StreetUtils.java#L123) correctly.

**Comment by mattwigway** [comment]
Hmm, good catch. We may want to take a more nuanced view of this: we probably do want to remove small pedestrian areas that are only connected to motorways (in airports for example). I think we should just not remove edges in subgraph pruning that are not traversable by walking.

Cycling adds another wrinkle. We could consider using the BICYCLE mode when pruning as it includes both bikeable and walkable edges (via bike walking, which I just implemented on my branch). That leaves pedestrian areas that connected to bikeable but not walkable ways. I don't know how common that is, but I can think of [examples](https://en.wikipedia.org/wiki/California_County_Routes_in_zone_G#/media/File:Foothill_Expressway.jpg).

**Comment by abyrd** [comment]
We originally began pruning islands because they can lead to confusing routing failures when a path cannot exit an isolated section of the graph. If we allow changing the traverse mode on an edge-by-edge basis when discovering the islands, from the perspective of any single mode we could still leave islands in the graph, causing similar problems. We could for example have a group of three car-traversable edges that were not properly connected, which could cause inexplicable routing failures if a drive-to-transit trip is calculated from near one of those edges.

I believe we need to do re-run the island removal procedure separately for each street mode, and only remove islands that are below a certain size (that contain a small number of edges). 

The OTP island removal become bizarrely complex because of contributed patches that take into account whether there are transit stops near the islands etc. We should completely avoid such things in our new implementation. Its point is to complain loudly when there are errors in the input data (small clusters of edges not connected to the network), and rip out the obviously broken parts of the data, without doing anything too clever or attempting auto-repair them.

**Comment by abyrd** [comment]
Although now that I think about it, an airport could legitimately contain a small number of isolated walking edges connected to a transit stop.

**Comment by mattwigway** [comment]
Yes, but if we snap to transit stops (which we're not currently doing) the airport case is fine because the narrative will just say something like "take B30 to Baltimore/Washington International Airport."

**Comment by hannesj** [comment]
Also real islands that are connected by ferries to the mainland should be walkable. Example is [Suomenlinna neighbourhood](https://www.openstreetmap.org/#map=16/60.1468/24.9819), which is connected by multiple ferry piers.

**Comment by andreyz** [comment]
Another real island example that's being pruned by current OTP implementation is [Stora Fjäderholmen](http://www.openstreetmap.org/#map=17/59.32841/18.17550) in Stockholm as well.

**Comment by buma** [comment]
This also removes "islands" which are actually car only normal short streets.
On all images green are forward edges which allows car orange dashed are forward edges which allow pedestrian.
Without removing islands:
![both1](https://cloud.githubusercontent.com/assets/1055967/11536029/06b92f9c-9917-11e5-9f77-f5ff84c3ab5c.png)
With removing islands:
![both2](https://cloud.githubusercontent.com/assets/1055967/11536031/07c7675a-9917-11e5-9b20-d2a0b123b4c3.png)

[osm location](http://www.openstreetmap.org/way/111489599#map=17/46.55643/15.62570)

I have no idea why less then half of roundabout is removed since all of it has foot=no.
Without removing island:
![island2](https://cloud.githubusercontent.com/assets/1055967/11536089/3d8f8b92-9917-11e5-8310-9d20bcc14e0f.png)
With removing island:
![noisland1](https://cloud.githubusercontent.com/assets/1055967/11536088/3d8eee6c-9917-11e5-8595-dd3b676e8b84.png)


[osm location](http://www.openstreetmap.org/#map=19/46.55797/15.65165)

I have currently disabled removing islands since routing is impossible with it.
