### ISSUE TITLE
Optimizing saving of EnumSets (edge flags)

### ISSUE THREAD

**Issue by buma** [conveyal/r5#28]
Currently flags are saved as ArrayList of EnumSets. EnumSets are great for that since all information is saved internally as one long (bitset basically) if number of enums is less then 64 (which it is currently). But problem is that it isn't serialized as such. Even default java serialization of EnumSet is saved as type of enum and array of Enums.

In FST (which we use) for serialization enumSet is saved as list of ordinal numbers of each enum together with class metadata for each enum in EnumSet.

I compared this together with sving enums as bitset in int/long and

`enumSetFST` is current way of saving enums.
`intFlags` is previous one (as troveIntList), `longFlags` (as troveLongList) if we need more then 32 flags.
FST is fast serialization Ser is java serialization. It can be seen that just enumflags are 26% of whole file size since all the *.dat files except network.dat has only the flags saved.

First I wrote new FST serializer which saves Enumset as int flag. File size did get lower from 8,6 M to 5,1. Then I wrote custom arrayList serializer which saves ArrayList of EnumSets as just primitive int array of flags each flag is bitset of enumset. This makes file size even smaller then previous Trove intMap (2,3 M) vs (2,8 M). The problem is that it uses twice as much memory for reading and writing since it needs to have flags in memory twice once as arraylist of enumset<edgeflags> and as int of bitsets of flags.

What do you think? It probably needs some more testing and error handling.
[gist](https://gist.github.com/buma/54601d12481ba88ee49e) with serializers.

usage: (you need one or the other)
```java
FSTConfiguration conf = FSTConfiguration.createDefaultConfiguration();
conf.registerSerializer(EnumSet.class, new MyEnumSetSerializer(), true);
conf.registerSerializer(ArrayList.class, new MyEnumSetListSerializer(), false);
FSTObjectOutput out = getConf().getObjectOutput(outputStream);
```

My branch with [tests](https://github.com/conveyal/r5/tree/enumFlagsOptimization) just start  it with `com.conveyal.r5.R5Main point --test path to graph directory` and it will load saved graphs and save it in different formats.

Sizes:
```
-rw-r--r-- 1 mabu users 8,6M nov 25 18:05 enumSetFST.dat
-rw-r--r-- 1 mabu users  23M nov 25 18:05 enumSetSer.dat
-rw-r--r-- 1 mabu users 2,8M nov 25 18:05 intFlagsFST.dat
-rw-r--r-- 1 mabu users 2,3M nov 25 18:05 intFlagsSer.dat
-rw-r--r-- 1 mabu users 4,1M nov 25 18:05 longFlagsFST.dat
-rw-r--r-- 1 mabu users 4,5M nov 25 18:05 longFlagsSer.dat
-rw-r--r-- 1 mabu users  32M nov 24 18:06 network.dat
-rw-r--r-- 1 mabu users  47M nov 25 11:01 network_ser.dat
-rw-r--r-- 1 mabu users  58M sep 14 07:31 slovenia-latest.osm.pbf
```

Custom FST enumSet serializer:
```
-rw-r--r-- 1 mabu users 5,1M nov 25 18:09 enumSetFST.dat
```

Custom FST ArrayList EnumSet serializer
```
-rw-r--r-- 1 mabu users 2,3M nov 25 18:10 enumSetFST.dat
```

**Comment by mattwigway** [comment]
Thanks for the thorough analysis! I'm not super concerned about the serialized size of the graphs (we store them in S3 which is almost unfathomably inexpensive). However, @abyrd has rightly pointed out that using enumsets means that there are a bunch of pointers to enumsets rather than a single primitive list of ints or longs.

**Comment by buma** [comment]
The only indirection is from ArrayList to enumSet. Enumset itself is just long with bits for enums.

It seems ArrayList is efficient to save objects (we don't gain anything probably with EnumSet[]): 
>ArrayList is one of the most efficient storage structures in JDK: it has an Object[] for storage plus an int field for tracking the list size (which is different from the array/list capacity = array.length). As long as you keep the actual objects in the ArrayList, it offers you near-optimal storage.

>RegularEnumSet utilizes the knowledge of the fact that there are less or equal to 64 values in the enum. It allows RegularEnumSet to use a single long to store all “enum present in the set” flags, rather than using `long[]` (utilized by JumboEnumSet or BitSet).

[RegularEnumSet source](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/util/RegularEnumSet.java#41).
[source](http://java-performance.info/memory-consumption-of-java-data-types-1/) of quotes.

So it seems for memory usage decision is between TIntList and ArrayList<EnumSet>. I'm not sure it is necessary to change them for now.

**Comment by abyrd** [comment]
Hi @buma, thanks for the analysis. The flags were originally stored as an array of primitive ints. Matt switched it over to use EnumSets, which is understandable: this is the appropriate built-in Java abstraction for what we're doing. But in typical Java fashion, it works by making a collection of pointers to (pointers to) data. I'm not immediately concerned about the size of the serialized graphs, but I am concerned about indirection and the size and locality in memory, and as a matter of design principle I want to avoid going down the path of pointer chasing and serializing big object graphs like we did in OTP.

It is of course still desirable to have a layer of abstraction and type safety on top of bit flags. The clean way to do this without creating zillions of pointers in Java (and the traditional way in less-OO programming) is to make static functions that operate directly on primitive value-typed fields:

`public static void setEdgeFlag (Edge edge, FlagEnum flag, boolean value)`
`public static boolean getEdgeFlag (Edge edge, FlagEnum flag)`

Where each option in FlagEnum has an explicitly associated integer value (`1<<0`, `1<<1`, `1<<2` etc.) You could of course also do it with constant ints but using Enums adds type safety with little or no overhead (probably).


It is true that there's an optimization in RegularEnumSet that avoids additional indirection for Enums with less than 64 different possible values. But if you look at the source for the abstract superclass EnumSet, you'll see that every EnumSet has two other fields:

```
final Class<E> elementType;
final Enum[] universe;
```

So that's a pointer-to-class-object, a pointer-to-array-of-Enum, and and array-of-Enum, for every EnumSet instance. It's a convenient abstraction when you need it, but is a step toward diluting the concept of R5 that I'd rather avoid, especially since the other flag technique is perfectly readable and maintainable.

**Comment by abyrd** [comment]
And re-reading this, I realize it can even be quite OO if we just put the get/set flag methods on the Edge cursor class. This is in fact how it was done before commit 116b498df4a3143661d97ac975ac6780c5662856. @mattwigway could we just switch back to the old style?

**Comment by mattwigway** [comment]
No objections here. I'm not sure in hindsight why I changed it.


-- 
 Matthew Wigginton Conway
 Transportation Analytics/Open Source
Washington, DC
indicatrix.org




---- On Thu, 26 Nov 2015 09:30:11 -0500 Andrew Byrd &lt;notifications@github.com&gt;wrote ---- 




And re-reading this, I realize it can even be quite OO if we just put the get/set flag methods on the Edge cursor class. This is in fact how it was done before commit 116b498. @mattwigway could we just switch back to the old style?

**Comment by abyrd** [comment]
I see now that there are also VertexFlags which are stored in List<EnumSet<VertexFlag>>. I'll switch them to int arrays as I did with the EdgeFlags.
