### ISSUE TITLE
Exact times causes crash with add-trips

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#290]
@marcovanderlinden reports that he is experiencing this crash with exact-times enabled on an add-trips modification:

![image](https://user-images.githubusercontent.com/566958/27633110-7f1dc366-5c30-11e7-86d5-a0c780c1445b.png)

It appears that the exact-times mode is not implemented for add trips, we need to add it.

**Comment by abyrd** [comment]
Now we are getting crashes any time exact-times is false!

**Comment by ansoncfit** [comment]
This issue rears its head again.  In a worker log:
```
09:16:25
java.lang.RuntimeException: This pattern ID specified in a scenario does not exist: 5b837a3f32b98e0ee389fa3d at com.conveyal.r5.profile.FrequencyRandomOffsets.randomize(FrequencyRandomOffsets.java:96) at com.conveyal.r5.profile.FastRaptorWorker.runRaptorForMinute(FastRaptorWorker.java:333) at com.conveyal.r5.profile.FastRaptorWorker.route(FastRaptorWorker.java:181) at com.conveyal.r5.analyst.T
09:16:25
401763 [qtp11050232-16] WARN com.conveyal.r5.analyst.cluster.AnalystWorker - Reporting errors in response to single-point request:
09:16:25
[com.conveyal.r5.analyst.error.TaskError@75c78448]
09:16:25
401765 [qtp11050232-16] INFO com.conveyal.r5.analyst.cluster.TimeGrid - Writing travel time surface with uncompressed size 9351 kiB
09:16:25
401893 [qtp11050232-16] INFO com.conveyal.r5.analyst.cluster.AnalystWorker - Travel time surface written, appending metadata with scenario application 1 warnings
09:16:25
401895 [qtp11050232-16] INFO com.conveyal.r5.analyst.cluster.AnalystWorker - Done writing
09:16:25
401898 [qtp11050232-16] INFO spark.http.matching.MatcherFilter - The requested route [/single] has not been mapped in Spark for Accept: [null]
```

**Comment by ansoncfit** [comment]
Here's the modification:
![image](https://user-images.githubusercontent.com/2173529/44672335-2570d280-a9f6-11e8-9199-a7a9f71dbb12.png)


Note that the key in the above exception (`5b837a3f32b98e0ee389fa3d`) is the _id of the modification.  But I think R5 is looking for the source trip.

**Comment by abyrd** [comment]
@ansoncfit the above text is what the front end is sending to the back end over HTTP?

**Comment by abyrd** [comment]
That exception is thrown in a block of fairly complicated code using integer indexes into the array `TripSchedule.phaseFromId`, just based on the fact that an entry is `null`. It looks like it's just expecting the phase fields to be set, including phaseFromTimetable.

**Comment by abyrd** [comment]
I created a test project with only a single add-trip-pattern modification. It has a single timetable that has exact-times enabled. I can perform a single point analysis using this modification with no problem. One strange thing is that worker logs show:

```
INFO com.conveyal.r5.profile.FastRaptorWorker - Prefiltering patterns based on date active reduced 1020 patterns to 0 frequency and 763 scheduled patterns
INFO com.conveyal.r5.profile.FastRaptorWorker - Performing 120 scheduled iterations each with 9 Monte Carlo draws for a total of 1080 iterations
```

So the scenario includes no frequency patterns at all, yet the worker is performing Monte Carlo draws, presumably based on the presence of this modification (which should not add any frequency based trips). When exact-times is disabled, we see these messages:

```
INFO com.conveyal.r5.profile.FastRaptorWorker - Prefiltering patterns based on date active reduced 1020 patterns to 2 frequency and 761 scheduled patterns
INFO com.conveyal.r5.profile.FastRaptorWorker - Performing 120 scheduled iterations each with 2 Monte Carlo draws for a total of 240 iterations
```

So the frequency trip exists now but the behavior is the same, Monte Carlo simulation happens. Interestingly even with the modification completely removed I see:

```
INFO com.conveyal.r5.profile.FastRaptorWorker - Prefiltering patterns based on date active reduced 1018 patterns to 0 frequency and 761 scheduled patterns
INFO com.conveyal.r5.profile.FastRaptorWorker - Performing 120 scheduled iterations each with 9 Monte Carlo draws for a total of 1080 iterations
```

So it looks like the exact times check box works, creating non-frequency trips, but the worker still does MC draws even when there are no frequency trips in the network.

**Comment by abyrd** [comment]
This problem is due to the iteration termination condition at https://github.com/conveyal/analysis-backend/blob/dev/src/main/java/com/conveyal/taui/models/AbstractTimetable.java#L57

The integer division determining the number of departures always truncates toward zero, so the length of the departures array is too small by one except in the special case where the active time range of the timetable is exactly divisible by the headway, in which case the array is the right length.

A short term workaround is to always use time ranges that are an exact multiple of the headway, e.g. if headway is 30 minutes and the timetable begins at 08:23 then it may end at 22:23, but not 22:22 or 22:24. 

Generally when trying to fill an array of a predefined length, the termination condition of the loop should be expressed in terms of the array index to avoid such problems. Superficially it looks less efficient to multiply rather than add at every iteration, but a) this is not at all in a critical path, b) that's a micro-optimization on a loop of at most a few dozen iterations, and c) any modern compiler (including JVM JIT) is going to auto-optimize this anyway and loop termination based on an array index is a better hint to both the compiler and future readers.

**Comment by abyrd** [comment]
Closing this and addressing in conveyal/analysis-backend#168

**Comment by abyrd** [comment]
I guess given that automation I should have left this open until the backend ticket is closed.

**Comment by ansoncfit** [comment]
The backend ticket is now closed.
