### ISSUE TITLE
Received a bikeshare access result that did not return the bike

### ISSUE THREAD

**Issue by evansiroky** [conveyal/r5#294]
I noticed that in some results on www.carfreeatoz.com that there were bikeshare access results where the bicycle was not returned to a bikeshare station.  A good visual example of this can be found with this query: http://www.carfreeatoz.com/planner?from=Arlington%2C%20VA%2C%20USA%20undefined&to=Alexandria%2C%20VA%2C%20USA%20undefined&modes=BICYCLE%2CBICYCLE_RENT%2CBUS%2CTRAINISH%2CWALK%2CCAR&start_time=7&end_time=9&days=M%E2%80%94F

I went ahead and extracted the raw r5 response pertaining to one of these options that didn't have a bikeshare off station and have uploaded it here: [r5-response.json.zip](https://github.com/conveyal/r5/files/1117598/r5-response.json.zip)

**Comment by mattwigway** [comment]
@buma do you know what is going on here?

**Comment by buma** [comment]
That is strange. I'll look into it.

**Comment by buma** [comment]
I can't reproduce the problem. With same from and to coordinates I can get a path from origin to first bike share but then my bike gets returned and tjen 16G is used and then Metroway. I'm not sure how this can happen since findBikeRentalPath can only return streetRouter with walk search from returned bike to all other vertices or null if origin couldn't be found. I can't see a way how streetrouter with only first two searches can be returned. Which commit of R5 is this? I tested on master.

**Comment by buma** [comment]
Strangely mode is also wrong. When bike is rented mode should be BICYCLE and is on my server but is WALK here for some reason.
