### ISSUE TITLE
Deal better with unlinked stops

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#33]
Once a TransportNetwork is built, we convert it into Transitive format. The last stage is to write out the stops, but layer.streetVertexForStop.get(sidx) can return -1 if the stop is not linked to the street.
This leads to the following exception:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
    at gnu.trove.list.array.TIntArrayList.get(TIntArrayList.java:283)
    at com.conveyal.r5.streets.VertexStore$Vertex.getLat(VertexStore.java:81)
    at com.conveyal.r5.transitive.TransitiveNetwork.<init>(TransitiveNetwork.java:69)
    at com.conveyal.r5.publish.StaticServer.main(StaticServer.java:43)
    at com.conveyal.r5.R5Main.main(R5Main.java:29)
```

**Comment by buma** [comment]
Probably we need to replace null with -1 and add -1 as noEntry value.

**Comment by abyrd** [comment]
There are no nulls, or I'm misunderstanding you. We just need to catch the -1 which means "no corresponding street vertex" and skip to the next transit stop. It should be a simple fix but I didn't have time to do it right away.

**Comment by buma** [comment]
If I understand the code correctly [here](https://github.com/conveyal/r5/blob/master/src/main/java/com/conveyal/r5/transit/TransitLayer.java#L274) we add a null if `streetVertexForStop.get(stop)` returns -1.

**Comment by mattwigway** [comment]
This is unfortunately somewhat nontrivial to fix, because we need to provide a latitude and longitude for every stop to Transitive. My first thought was to just remove unlinked stops from the transitive network because they can't be used to board or alight, but I then realized that they can be used for loop transfers (it's possible to get off at a stop that is unlinked and then board another transit vehicle from the same stop, even if you can't reach the street network). We still need to render those stops correctly. I think we'll have to save latitude and longitude information in each stop.

**Comment by abyrd** [comment]
Or we could just create street vertices that have no edges connected to them when in an area that has no streets to link to.

**Comment by mattwigway** [comment]
Yes, that's what we should do. That won't affect splitting, and we already have a bunch of vertices with no edges as a result of island removal.

**Comment by mattwigway** [comment]
Wait, do we still use the Transitive stuff for Modeify?

**Comment by ansoncfit** [comment]
We're no longer supporting Modeify in R5.  Closing.
