### ISSUE TITLE
How to handle date/time in profile request?

### ISSUE THREAD

**Issue by buma** [conveyal/r5#37]
Currently we have date as joda `localDate` in unknown timezone and time in `fromTime` and `toTime` as seconds since midnight. We have two options to interpret this:
- As date and time in graph timezone
- As date and time in UTC

This is necessary in routing since some turn restrictions are based on time and if we have graphs with only one timezone first option is OK but if we have graph on a border of timezones second option is probably better since then all of the times will be converted to UTC.

Another question is do we need to specify time as number of seconds since midnight? It would be nicer IMHO if we could specify it as time `HH:MM:SS` and timezone. Or even date time together.

**Comment by abyrd** [comment]
For reference: The ZoneId parameter was just causing problems because it's not a concrete type and couldn't be instantiated when deserializing from JSON. I added some de/serializer classes to make it work. I think @buma 's suggestion makes more sense, just using a single field for datetime with time zone.
