### ISSUE TITLE
Allow non-walk egress modes

### ISSUE THREAD

**Issue by ravi9884** [conveyal/r5#426]
Actual
In multimodal transport r5 uses bicycle only for the first leg of the journey. The last leg always uses foot.

Expected
If there is a bike route at the final leg of the journey, it should be used instead of walking.

**Comment by ansoncfit** [comment]
Our current implementation of LinkedPointSet means some effort is needed for non-walk egress modes. `makeStopToPointDistanceTables` uses `stopToVertexDistanceTables` (distances for WALK computed when the TransportNetwork is built and serialized with it).

Linking a pointset by bicycle would require recalculating the `stopToVertexDistanceTables` (which will be different from the ones serialized with the network if cyclists and pedestrians use different ways), extending these new distances to targets, and revising PerTargetPropagator to use the requested bikeSpeed instead of walkSpeed.  

Linking a pointset by car would require computing stop-to-vertex and vertex-to-target _times_, as total distance won't work (given varying speeds). To minimize other changes needed, we could use the convention of saving the times in the distance tables, then setting `PerTargetPropgator.speedMillimetersPerSecond` to 1 when `request.egressMode = CAR`.

**Comment by ansoncfit** [comment]
See also https://github.com/conveyal/r5/issues/450
