### ISSUE TITLE
Bike rental support

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#43]
We need to support bike rental. There are two ways to do this:
1. The way it was historically done in OTP, where there are incomparable states and we do the whole search at once. It complicates the search code somewhat as we have to store multiple states at each vertex.
2. Instead of running the walking and biking search at once, we could first run a walking search, then a multi-origin cycling search from all reached stations, then a multi-origin walking search _using the same output tree as was used in the original search_ from the reached bikeshare stations.

I kind of prefer the second option (and not just because I thought of it) because it neatly removes the need for multiple states per vertex, which can be a debug nightmare.

**Comment by abyrd** [comment]
After our conversation the other day, completely agreed. We should aim to have one dominant state per vertex, then call that same procedure multiple times in a row with multiple starting points for the different segments of access/egress.

Not having multiple states per vertex means we need to handle turn restrictions with extra vertices and graph topology, but we already decided to do it that way.

**Comment by mattwigway** [comment]
Here's the file we'll initially use. We can use the splitting code to link it into the graph. http://www.capitalbikeshare.com/data/stations/bikeStations.xml

**Comment by mattwigway** [comment]
For now we won't even look at the number of bikes available.

**Comment by buma** [comment]
When graph is build bike stations are read from XML specified in jsonConfig. They are added to the graph as vertices with BIKE_SHARING flag. And BikeRentalStation objects are added to map in streetLayer. Map keys are streetVertex index values are BikeRentalStation objects with name, id, bikes/spaces available. This is used since number of bikeRentalStations is small and it makes no sense to add those things to each vertex.

When searching for path:

1. one walk search from start to all the bike sharing stations is made. 
2. one bike search from the bike stations. Here each bike stations found in previous search is added to new search as start node with previous time and weight.
3. walk search from bike stations to the end

Path is constructed from those three searches. Time gaps for renting/dropping bike are also added. 1 minute for renting and 30 seconds for dropping of. I also added isBikeRental boolean to state which is true if vertex in current state represents bikeRental station. This is used when showing path to the user to add bikeRentalStations in API response.

Debug GraphQL API response also shows bikeRental station as circles. Currently it shows whole bike rental path as one in a map(It isn't split based on mode of transport).

**Comment by buma** [comment]
Paths in debug client are now showed in correct colors. (Walking with bike in cycling mode is in WALK color even though Leg mode is BICYCLE) same with bike rentals.
