### ISSUE TITLE
Find suboptimal paths

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#45]
In order to replace the routing engine in Modeify, we need to be able to find suboptimal paths. The approach @abyrd and I had discussed was to find paths through repeated banning. The problem with this is that it becomes a combinatorial problem - suppose you have a path A -> B -> C, you then have to ban A, B, C, AB, AC, BC and then repeat. We have not conclusively shown that this is infeasible. I suspect though that we'll need a heuristic to choose what to ban.

**Comment by mattwigway** [comment]
Although we can use goal direction which might make it tolerably fast.

**Comment by mattwigway** [comment]
Another option would be to use McRAPTOR, which saves multiple states per stop, but that could easily turn into a mess.

**Comment by mattwigway** [comment]
The McRAPTOR approach is basically what we do in Modeify, we're finding trips that are less than five minutes slower than the fastest path (this is what suboptimalMinutes does).

**Comment by mattwigway** [comment]
This is a _k_-shortest-paths problem, which has been applied to transit networks [before](https://hal.archives-ouvertes.fr/hal-01180453/document)

**Comment by abyrd** [comment]
As in implementing bike rental and park-and-ride, I would prefer a solution based on iterative reuse of a simpler function (rather than a single call to a more optimized, more clever function) as long as that doesn't cripple run time. Let's try the combinatorial banning thing before we do anything fancy. If I'm not mistaken we don't even need to ban every combination of used trips. What we're really trying to do is ban exact sequences of trips that have already been seen, but we can't for example ban trip sequence A,B,C at the moment we board C because that amounts to resource-constraint type pruning. We can however prune when boarding trip A, which amounts to banning all trip sequences that have A as a prefix. So we should be able to somehow factor out common prefixes, reducing the combinatorial explosion.

**Comment by mattwigway** [comment]
I'll create a class that returns a Collection<Path>.

**Comment by mattwigway** [comment]
See the class McRaptorSuboptimalPathProfileRouter.

**Comment by mattwigway** [comment]
We're having issues with the bike routes biking very close to the destination and then taking a bus one stop just to make it a transit trip.

**Comment by mattwigway** [comment]
We can fix that particular issue by reducing the bike LTS. But we will have the same problem with cars.

**Comment by mattwigway** [comment]
I'm pretty happy with the results. I now do the street searches using a generalized cost (adding extra cost for cycling or driving to prevent cycling/driving trips that are only marginally faster than walking). It computes in about 5s in DC, which is not fantastic but is already better than the existing solution.

My main question now is how you determine what access mode was used to reach a particular stop @buma. If you look in PointToPointQuery::combineMultimodalRoutingAccessTimes, all of the access and egress modes are combined into a single access times map. Perhaps we need to create a parallel access modes map?

**Comment by buma** [comment]
>My main question now is how you determine what access mode was used to reach a particular stop
Currently I don't. I just use all of access and egress modes when creating itineraries. But this can of course be problematic.

What about one multimap of legmode->endstopIndex. Then we would now which mode was used for which stopIndex.

We also need to know earliest and latest accessTime and egress time to know what time to use in search. Since it isn't the same as profileRequest time.

And during response creation I need to add filtering that if you request trip starting from 7. And it actually starts at 6:45 since you need to come to the stop that this isn't returned.

**Comment by mattwigway** [comment]
Don't you want a map from endStop -> legMode? I'm not sure I understand the time comment; we do take into account the access and egress time when building paths, and the itineraries in PathWithTimes.itineraries should respect the time window, if they don't it's a bug.

**Comment by buma** [comment]
Yeah endStop -> legMode makes more sense. Access and egress time seems to be taken into account when finding Paths. So the only thing needed is to know which accessMode was used to get at the stop at specific time.

Currently it seems for each stop only fastest access mode is saved in combineMultiModal which makes sense, but we need to save which mode that was. I think endStop -> legMode would be enough for that to work. And currently combineMultiModal is filtering on state time but getReachedStops returns weight not time.

I'll do that on Tuesday.

**Comment by mattwigway** [comment]
OK. Combinemultimodal is filtering on time plus modal penalties. getReachedStops should probably return time.

**Comment by buma** [comment]
I added stopMode(access/egress)Map which has mapping from stop to LegMode and is used in response creation.

**Comment by mattwigway** [comment]
Thanks!
