### ISSUE TITLE
GraphQL API

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#48]
We need a stable trip planning API in order to replace OTP with R5 in Modeify.

**Comment by abyrd** [comment]
We expect this to look like the existing profile routing API in OpenTripPlanner, but with optional tables of times at which each segment of each option can be carried out.

**Comment by buma** [comment]
According to [issue](https://github.com/graphql/graphql-js/issues/111) it seems that GraphQl by itself doesn't do deduplication. It [seems](https://gist.github.com/wincent/598fa75e22bdfa44cf47) that this is [Relay](https://facebook.github.io/relay/)'s job:
>Performance: All queries flow through the framework code, where things that would otherwise be inefficient "N+1" query patterns get automatically collapsed and batched into efficient, minimal queries. Likewise, the framework knows which data have been previously requested, or for which requests are currently "in flight", so queries can be **automatically de-duplicated** and the minimal queries can be produced.

So If I understand Relay correctly if we send a request for trip with routes [A,B,C] and tripPatterns [A:1, A:2, B:3] we get all of them. But on next request where we have tripPattern [A:1, C:3] A:1 is read from cache and isn't requested at all since Relay has a local [cache](https://facebook.github.io/relay/docs/thinking-in-graphql.html#caching-a-graph). But for the code requested plan all this is transparent.

I also tried to play with relay locally but there were some problems running it that I couldn't figure out.

For now I moved list of "tripPatterns" to a list. https://github.com/conveyal/r5/commit/9d4d28529d1b13093bd146859c3c2ab3bf2ccaa5

I think that we need to support those transit modes combinations:

1. A -> CAR -> B 
2. A -> WALK -> B
3. A -> CYCLE -> B
4. A -> CYCLE -> WALK with bike -> CYCLE -> B
5. A -> WALK -> CYCLE_RENT -> WALK -> B **(bike renting)**
6. A -> WALK -> CYCLE_RENT -> WALK with bike -> CYCLE_RENT -> WALK -> B **(bike renting where we need to walk at some part)**
7. A -> WALK -> TRANSIT -> WALK -> B **(normal transit without transfer)**
7. A -> WALK -> TRANSIT -> WALK -> TRANSIT -> WALK ->B **(transit with transfer)**
1. A -> CYCLE -> WALK -> TRANSIT -> WALK -> B **(B+R)**
1. A -> CAR -> WALK -> TRANSIT -> WALK -> B **(K+R, P+R)**

What we can support now with profile like API is 1-3 and 7.
For 4 we only need to add walking bike property in streetEdge, for 5 we need to add bike_renting property and add bike rentals stations. 6 is supported if we support 4 and 5.
Switching between CYCLE and WALK in B+R (9) and CAR and WALK in P+R (10) can be also supported with flags in streetEdges.
8. is supported in a way since each transit can have multiple transfers but there is no way to represent walking from one stop to another.

I don't know where would be good place for bikeRental stations/P+R/B+R stations. In OTP
We have Itinerary with legs and steps. So for Bike rental we would have itinerary from A to B with minimally 3 legs:
1. Leg walking from A to Bike rental station A_1
2. Leg cycling with rented bike from rental station A_1 to rental station B_1
3. Leg Walking from rental station B_1 to B
Each of those legs have `from` and `to` object where we have location and names, arrival, departure time, id of station etc. If we represent all of this as one profile `access` object with streetEdges we would need to add some kind of from/to object to each streetEdges. They would be optional but would be used when mode changes and to show P+R/B+R and bike rent stations. Probably best way would be to just add ID. And then return all in a special list.

I propose adding unique ids to each access, egress and transit. And to add connection element which would have:
- walkTime
- transitTime
- distance
- transfers
- list with ID of access, transit and egress that go together or just access if this is street only trip

And another object same as access/egress called middle where all the edges and info for walking between transit stops are and each segment pattern except the last would have ID saved to the middle object. So the path can be fully reconstructed.

We also need to add list of startTime and endTimes to segmentPatterns and list of arrival/departure delays. List because same segmentPattern can be used at different times of day if it is frequent enough.
I'll need to look what to to with times. Since each transit can have multiple times but for access and egress we will probably have only one if stops are the same. But paths are not necessarily the same at different parts of the day (traffic speed, conditional turn restrictions, road closures etc.)

This is short version. I'm working on proof of concept.

**Comment by buma** [comment]
This is compacted response of example for 8:
```
d [ 12 ] routes 1/21, 16/4/18/19/6/2/20 via CITY CENTER
   Access:
    Mode: BICYCLE streetEdges: 52
   Transit:
     Routes:  1 21
     LJUBLJANSKA - UKC -> CITY CENTER
        MARPROM:1:0:02 [ 0 ] 1 to AP Mlinska (MARPROM:68)
        Ljubljanska - UKC  ->  CITY center
        MARPROM:14:0:01 [ 1 ] 21 to AP Mlinska (MARPROM:68) from Ljubljanska 140 (MARPROM:222)
        Ljubljanska - UKC  ->  CITY center
        MARPROM:14:0:03 [ 2 ] 21 to AP Mlinska (MARPROM:68) from E.Leclerc - obračališče (MARPROM:217)
        Ljubljanska - UKC  ->  CITY center
     Routes:  16 4 18 19 6 2 20
     CITY CENTER -> Kneza Koclja - Vetrinjska
        MARPROM:3:1:01 [ 0 ] 6 to Vzpenjača - obračališče (MARPROM:145) from AP Mlinska (MARPROM:68)
        CITY center  ->  Kneza Koclja - Vetrinjska
        MARPROM:4:1:01 [ 1 ] 18 to Pekre - trgovina (MARPROM:238) from AP Mlinska (MARPROM:68)
        CITY center  ->  Kneza Koclja - Vetrinjska
        MARPROM:2:1:02 [ 2 ] 2 to Kardeljeva - Borštnikova (MARPROM:63) from AP Mlinska (MARPROM:68)
        CITY center  ->  Kneza Koclja - Vetrinjska
        MARPROM:12:1:01 [ 3 ] 19 to Šarhova - obračališče (MARPROM:160)
        CITY center  ->  Kneza Koclja - Vetrinjska
        MARPROM:5:1:01 [ 4 ] 4 to Limbuš - Marof (MARPROM:150) from AP Mlinska (MARPROM:68) via Lesarska šola - obračališče (MARPROM:284)
        CITY center  ->  Kneza Koclja - Vetrinjska
        MARPROM:10:1:01 [ 5 ] 16 to Zg. Duplek - obračališče (MARPROM:311)
        CITY center  ->  Kneza Koclja - Vetrinjska
        MARPROM:13:1:04 [ 6 ] 20 to Grušova - obračališče (MARPROM:378) from Melje - obračališče (MARPROM:19) like trip MARPROM_1999
        CITY center  ->  Kneza Koclja - Vetrinjska
        MARPROM:2:1:03 [ 7 ] 2 to Razvanje - obračališče (MARPROM:67) from AP Mlinska (MARPROM:68)
        CITY center  ->  Kneza Koclja - Vetrinjska
   Egress:
    Mode: WALK streetEdges: 16
```
Each of those trip patterns like `MARPROM:14:0:03 [ 2 ] 21 to AP Mlinska (MARPROM:68) from E.Leclerc - obračališče (MARPROM:217)` have multiple times when it runs for example (`'07:05', '07:20', '07:35', '07:50', '08:05'`) I added to each segmentPattern 4 lists.
2 for origin stop(fromArrivalTime, toArrivalTime) and 2 for destination stop(toArrivalTime, fromArrivalTime). For realtime 4 extra lists would be needed for realtime arrival/departure delay.

So if transit appears only once this a trip without transfers. I added element of itinerary which looks like that in yaml (since it is more compact then json):
```yaml
itinerary:
- connection:
    access: [0]
    egress: [0]
    transit:
    - {pattern: 0, time: 0}
    - {pattern: 0, time: 0}
  distance: 650
  duration: 36584
  endTime: '2015-12-16T16:26:89+00:00'
  startTime: '2015-12-16T16:00:39+00:00'
  transfers: 0
  transitTime: 4576
  waitingTime: 462
  walkTime: 2223
  walkingDistance: 4857
```
Itinerary can have multiple connections. Each connection is same as Itinerary in OTP.
AKA trip from A to B at a specific point in time. It consists of access part, transit part and egress part. If this is direct route transit and egress is missing. Transit has same number of elements as transit in option. Each element consists of pattern index that is used in specific transit and time index in each pattern.
Since bus in first pattern can have a trip 0 from 7:00 to 8:15 but after transit trip which runs from 8:10 to 10:15 and we need to chose trip which starts with a later time maybe trip in a same pattern with next time index. But trip with this stoptime can be chosen with second pattern.

Each transit also has middle_id which is ID of a middle part from one stop to the next when transferring.

Currently middle, access and egress legs don't have times by itself. They only get times from itinerary based on duration of a trip and transit time table. This works as long as we don't have time specific street graph.(Time based turn restrictions, road closures, etc.). If we support this we need to add startTime and endTime to those legs too.


Examples of responses for 1-6: [non-transit](http://www.jsoneditoronline.org/?id=e5d43d9ee69ae95653e4baf23b046a04).
And [example](http://www.jsoneditoronline.org/?id=e7a5452f64acbe1544e6e7d89259537a) of response for 8. 7 is similar but doesn't have middle. 9 and 10 are different only in access parts.

**Comment by buma** [comment]
In GraphQL branch `from`, `to` coordinates are read from query and geometry, distances and duration for directTrips are returned as GraphQL profileResponse.

**Comment by abyrd** [comment]
Hi @buma. I was reviewing tickets and progress with @mattwigway a while ago. We were taking a closer look at this ticket and the API, and had a few questions. 

First, why are the "middle" sections (the transfer segments) referred to by numbers in the transit segments? Could they just be placed in-line in the transit segments? Is this because they repeat or are somehow reused in multiple places? 

Second, we see in your raw JSON response that trip patterns are referred to by ID rather than having all their detail included. This hints at the kind of de-duplication we were hoping to achieve, but do you have a plan on where to place the detailed trip pattern descriptions in the response? I see above you have referred to commit 9d4d285, have there been any further developments in this direction?

Finally, it seems that Relay is more about cacheing requests on the client side than about including de-duplicated elements in-line. If this is the case then it's not really what we're looking for. Just let us know if it's not clear what we're trying to achieve here.

**Comment by buma** [comment]
Middle sections can be also placed into transit segments I put them at the same level as access/egress for now because it seemed logical since they are part of non-transit leg. I also added routeIndex to transitSegment so that route information can be shown without using whole tripPatterns since they aren't supported yet. I'll see If I'll keep it after tripPatterns are supported. It is a little problematic since GraphQl doesn't support maps. It would be easier to return things as a map from index/id to data.

Multiple transit patterns can use same middle part so that's why it also makes sense for them to be outside transitSegment. They aren't supported yet. It isn't a large change and I wanted to create everything from start to finish to have something to test. The biggest issue is which mode to use in middle parts.

I didn't add TripPatterns yet since I didn't needed them for now. But I'll add them soon.

**Comment by buma** [comment]
TripPatterns are added now. They differ a little from modeify response since Modeify had directionID in each trip but R5 seems to have directionID in tripPattern. There is also curently no way to retturn pattern desc, trip shapeID and trip headsign.

**Comment by mattwigway** [comment]
This is more or less done. @buma will write documentation including example requests/responses. We'll also move the transfers (middle segments) into the transit component.

**Comment by mattwigway** [comment]
We'll also include trip IDs in trips, and then use that to look up information in the GTFS MapDB, which we'll keep around. We'll use the pattern index as the pattern ID. We'll add a GTFS file name to TripPattern and add a list of GTFS files names for stops. This won't be too large if we do it right, as we'll just have a bunch of pointers to the same string.

**Comment by buma** [comment]
Middle is now moved to TransitSegment.

**Comment by buma** [comment]
AFAIK only P+R and B+R info is missing in response, documentation and some fields are not filled yet (duration in transit, waiting time) after that this should be finished. This will probably happen tomorrow.

**Comment by buma** [comment]
I added some documentation in [R5 Docs](https://github.com/buma/R5Docs)
