### ISSUE TITLE
Not allowed links in StreetPath 

### ISSUE THREAD

**Issue by YOxan** [conveyal/r5#601]
Hello guys! In the [beam](https://github.com/LBNL-UCB-STI/beam) we are strongly rely on R5 router and using that a lot. We found that there is a problem sometimes when we request the path routing: in the response we get the links which are not allowed for set street mode. I prepared basic example [example](https://github.com/LBNL-UCB-STI/beam/blob/AK/%232570-available-modes/src/main/scala/beam/utils/router/Main.java) to demonstrate that . This one is runnable through the gradle stuff if you want to debug. 

Briefly, it sets the original with link which are not allowed for `StreetMode.CAR`, like here 
```
EdgeStore.Edge startEdge1 = main.edgeById(20109); //This link doesn't have mode ALLOWS_CAR
EdgeStore.Edge stopEdge1 = main.edgeById(66763);
```
and then set it through 
```
VertexStore.Vertex startVertex = vertexById(startEdge.getFromVertex());
VertexStore.Vertex stopVertex = vertexById(stopEdge.getFromVertex());

....

streetRouter.setOrigin(startVertex.getLat(), startVertex.getLon());
streetRouter.setDestination(stopVertex.getLat(), stopVertex.getLon());
streetRouter.route();
```

Once we debug this we get back following response which contains unexpected link at the start. Also that happens to the beginning and ending of the route sometime, and not to the links in the middle of path. The debug info is here:
```
Failed with path where edge are:
20109 -> Edge from 11084 to 11083. Length 52,746000 meters, speed 40,212002 kph. SIDEWALK ALLOWS_PEDESTRIAN ALLOWS_WHEELCHAIR LINKABLE BIKE_LTS_4
33528 -> Edge from 11083 to 8663. Length 146,472000 meters, speed 48,276001 kph. SIDEWALK ALLOWS_PEDESTRIAN ALLOWS_BIKE ALLOWS_CAR ALLOWS_WHEELCHAIR LINKABLE BIKE_LTS_4
15014 -> Edge from 8663 to 8664. Length 107,268000 meters, speed 40,248001 kph. SIDEWALK ALLOWS_PEDESTRIAN ALLOWS_BIKE ALLOWS_CAR ALLOWS_WHEELCHAIR LINKABLE BIKE_LTS_1
...
```
As you can see the first link in the route is not allowed for `StreetMode.CAR`. What could be the reason of such a behavior? Thanks in advance!

**Comment by abyrd** [comment]
Hi @YOxan, indeed it doesn't make sense for a path to begin with a non-car edge when the car mode is specified. Thanks for including a link to example code. We took a look at this today and can't immediately find any way the first edge traversal can be on a non-car edge, since the setOrigin call only considers edges with the right flags.

We noticed though that you seem to be using a fork of R5 with some major modifications to the routing code. Notably, your StreetRouter constructor takes several cost functions as arguments, including a travelTimeCalculator which seems to be hard-wired to return 10 for every edge. Since we don't know what has been changed in the router, it's hard to guess what could be causing this.
