### ISSUE TITLE
Build fails on pushed tags

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#627]
If you push a branch and the head commit on that branch is also a tag, the build will produce an artifact with that tag as the version number. However, if you push the tag itself (rather than the branch containing the tagged commit), the build will fail with the following error:

```
Execution failed for task ':createVersionProperties'.
> java.lang.NullPointerException (no error message)
...
BUILD FAILED in 47s
```

Looks like `gitVersion()` in the Gradle script must be returning null when building a pushed tag.

**Comment by njanakiev** [comment]
I've found the same issue when using specific tags or commits. The problem was located in `build.gradle` in the `createVersionProperties` task, where it tries to get the branch name with `details.branchName` which results in null. Apparently a detached HEAD in git has no branch name associated with it.

I fixed it with the following workaround:

```bash
git clone --branch v6.2 https://github.com/conveyal/r5 .
git checkout -b dev
```

**Comment by abyrd** [comment]
I fixed this in a recent commit using the ?: operator to provide a default string when no branch is defined.
