### ISSUE TITLE
Don't perform multiple iterations per minute unless the transit network has frequency-based routes

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#661]
I remember a comment somewhere explaining why we choose to repeat results to obtain an expected/requested number of iterations. But I don't think we need to perform multiple iterations per minute.

**Comment by abyrd** [comment]
I think there are two places results are replicated to match fixed array dimensions. 

The first place is TravelTimeReducer#recordUnvaryingTravelTimeAtTarget. That yields "only" a 5x replication of results for non-transit cases, so it is not clearly problemaic and the comments don't mention eliminating replication. Replication here probably does increase network traffic so it's a candidate for optimization, but a) repetition should be well compacted by gzip, and b) non-transit is not our dominant use case. So it may not be worth the complexity of a special mechanism for workers to tell the frontend that the response contains less percentiles than were requested.

The second place, and probably the one @ansoncfit was thinking of is FastRaptorWorker L431-435:

            // If there are no frequency trips, return the result of the scheduled search, but repeated as many times
            // as there are requested MC draws, so that the scheduled search accessibility avoids potential bugs
            // where assumptions are made about how many results will be returned from a search, e.g., in
            // https://github.com/conveyal/r5/issues/306
            // FIXME on large networks with no frequency routes this seems extremely inefficient.
            // It may be somewhat less inefficient than it seems if we make arrays of references all to the same object.
            // TODO check whether we're actually hitting this code with iterationsPerMinute > 1 on scheduled networks.
            //      maybe we should even require that iterationsPerMinute == 1 for non-freq searches in an assertion.
            //      checkState(iterationsPerMinute == 1); int[][] result = new int[1][];

Here the result (and network traffic) inflation could be massive depending on the request parameters. But perhaps more importantly, we have added complexity from defensive code that tries to prevent confusing the two or three different target numbers of iterations floating around: one in the request itself (which may not divide evenly into the number of minutes and may contain special-purpose values like zero), the actual number of iterations that would be appropriate for an MC computation (never zero, and always a multiple of the number of departure minutes), and the number actually used in the calculations, which might be equal to the number of minutes if MC is deemed unnecessary (half-headway is selected or there's simply no pure-frequency transit).

While we are working in the weeds this far down in the routing code, we should probably follow the advice in the comments and eliminate this whole conditional clause. Rather than defending against mismatched array lengths by copying, we should add more assertions that arrays and lists are the expected size and if they are not, fix the problem at the root.

The root of the problem appears to be the three potentially different coexisting numbers of iterations mentioned above, along with methods that calculate them but whose results can be overwritten. It looks like FastRaptorWorker.monteCarloDrawsPerMinute is not actually the number of draws used in the computation. It contributes to that number, but is superseded by a local variable iterationsPerMinute that may be different. 

Ideally only the number of monte carlo draws on the request should ever contain a special value like zero or a number of iterations that must be adjusted to be a multiple of departure minutes, to faithfully reflect what was received from the UI. Once it is fed into the calculation process on a worker, that number should be converted in a single step to a true quantity of total iterations and iterations per minute, which will be used consistently everywhere. No field should ever serve multiple roles of reflecting API input, or representing a target number of MC iterations, or representing the true number of iterations when MC is disabled.

**Comment by abyrd** [comment]
An example: at FastRaptorWorker L337 we create a local variable iterationsPerMinute that is equal to the instance field monteCarloDrawsPerMinute but is overwritten with 1 in a special case where boardingMode == MONTE_CARLO. It can be confusing to understand how large result arrays are expected to be, and generally what the routing and propagation is doing, when monteCarloDrawsPerMinute is not the actual number of draws being computed per minute.

It seems to me that the special value of 1 should be produced in a centralized location by method ProfileRequest#getMonteCarloDrawsPerMinute this is used uniformly everywhere. The apparent problem is that the boarding mode of HALF_HEADWAY is set in the FastRaptorWorker and not known to the request object. But the boarding mode is itself derived from the number of monte carlo draws in the request, so it should be possible to refactor the logic.

**Comment by ansoncfit** [comment]
Fixed in https://github.com/conveyal/r5/pull/634
