### ISSUE TITLE
Turn-by-turn directions

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#70]
We need turn-by-turn directions for access and egress modes (incl. biking, driving)

**Comment by mattwigway** [comment]
Prior art: https://github.com/opentripplanner/OpenTripPlanner/blob/master/src/main/java/org/opentripplanner/profile/DCFareCalculator.java

**Comment by mattwigway** [comment]
We also need to include names. We'll include the OSM way IDs on each edge (this will be a simple TLongList), and then we'll use that to look up the tags in the origin OSMLib MapDB.

**Comment by buma** [comment]
Currently Turn by turn directions have Relative and absoluteDirection, distance, stayOn (This is true if streetName is the same as previous instruction) and are compacted.
This means that multiple steps which are all on the same street with same CONTINUE instruction are joined into one step.

Direction calculation is currently little buggy since I don't use distances in meters in Linestring angle calculation.

I need to add roundabout exit support and highway exit.

**Comment by mattwigway** [comment]
I think for the time being let's leave off roundabout exit support; just saying turn onto such-and-such a street (combined with the map view) should be fine.
