### ISSUE TITLE
Create separate limits for distance and time

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#71]

**Comment by buma** [comment]
There are two limits in streetRouter now:
- distanceLimitMeters
- timeLimitSeconds

First nonzero one is used.
IMHO it would be better to have both limits be private and have a setter for them which makes sure to set other to 0 if one is set. Since now you can set timeLimitSeconds and forgot that distanceLimitMeters is set by default and distanceLimitMeters will be used instead of timeLimitSeconds.

I also added duration to the state since currently it only has current time. From which you can get duration in simple routing since you can get fromTime from profileRequest and calculate duration during routing. But in complex routing (like Bike sharing and P+R) which consist from multiple streetRouter requests it is impossible to get specific start time since each start state can have a different start time since it depends on time to this state with different mode of transportation and I didn't found better way to do it.

**Comment by mattwigway** [comment]
Aren't there cases where you want to set both limits though?

On Tue, Feb 9, 2016 at 11:06 AM, Marko Burjek <notifications@github.com>
wrote:

> There are two limits in streetRouter now:
>
>    - distanceLimitMeters
>    - timeLimitSeconds
>
> First nonzero one is used.
> IMHO it would be better to have both limits be private and have a setter
> for them which makes sure to set other to 0 if one is set. Since now you
> can set timeLimitSeconds and forgot that distanceLimitMeters is set by
> default and distanceLimitMeters will be used instead of timeLimitSeconds.
>
> I also added duration to the state since currently it only has current
> time. From which you can get duration in simple routing since you can get
> fromTime from profileRequest and calculate duration during routing. But in
> complex routing (like Bike sharing and P+R) which consist from multiple
> streetRouter requests it is impossible to get specific start time since
> each start state can have a different start time since it depends on time
> to this state with different mode of transportation and I didn't found
> better way to do it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/r5/issues/71#issuecomment-181930937>.
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by abyrd** [comment]
I see no problem with having both limits set at the same time (whichever gets hit first). I have developed an innate mistrust of anything that requires accessor methods ;)

**Comment by mattwigway** [comment]
I'd say though that Marko has a valid concern, so I'd propose the following:

1) have both parameters default to 0,
2) show a warning when both are set,
3) show a warning when neither is set

Matt

On Tue, Feb 9, 2016 at 11:45 AM, Andrew Byrd <notifications@github.com>
wrote:

> I see no problem with having both limits set at the same time (whichever
> gets hit first). I have developed an innate mistrust of anything that
> requires accessor methods ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/r5/issues/71#issuecomment-181950855>.
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by buma** [comment]
I changed as suggested. I also checked that some distance limit was set everywhere route was used since previously default value was 2km.

Internally if limit is 0 it is set to Integer.MAX_INT because if it would be used as 0 no routing would be done.
