### ISSUE TITLE
RegionalAnalysisController#getScenarioJsonURL is broken. Scenario ID does not exist on embedded request.

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/r5#765]
Newly created `AnalysisWorkerTask`s populate their scenario ID at `task.scenario.id`, old tasks populate it at `task.scenarioId`. We still use the old version in the `getScenarioJsonURL` method. This will always fails at the `checkNotNull` assertion with new regional analyses. See here:

https://github.com/conveyal/r5/blob/ebbd53b3079858a7ac7fbb32b0119350a15730b2/src/main/java/com/conveyal/analysis/controllers/RegionalAnalysisController.java#L536-L538

This `scenarioId` is generated when the regional analysis is created and should not be confused with the `Scenario` model's `_id`. See here:

https://github.com/conveyal/r5/blob/ebbd53b3079858a7ac7fbb32b0119350a15730b2/src/main/java/com/conveyal/analysis/models/AnalysisRequest.java#L169-L172

1. We should determine if the old style (`task.scenarioId`) is used anywhere else. 
2. If it is not, we should update the `getScenarioJsonURL` method to use the new style (`task.scenario.id`) and 
3. Run a migration on old regional analyses and put the scenario ID there.
4. Add an end-to-end test that downloads the scenario JSON.

Other related code that should be commented on or updated / deprecated:

https://github.com/conveyal/r5/blob/ebbd53b3079858a7ac7fbb32b0119350a15730b2/src/main/java/com/conveyal/r5/profile/ProfileRequest.java#L171-L179

**Comment by abyrd** [comment]
I just traced through the related code in hopes of recording some more context for posterity, and ensuring we don't introduce any new problems when patching this. 

This change was part of #742 that shifted to sending the backend a list of modifications instead of using integer "variants". The first thing to note is that we're specifically concerned here with RegionalTask, the subclass of AnalysisWorkerTask used in regional analyses (the other subclass being TravelTimeSurfaceTask used for single point analysis). The broken API endpoint is attempting to fetch the scenario for a completed regional analysis, and needs to look up the identifier/filename for that scenario on the RegionalTask within a RegionalAnalysis in the database.

Looking at the changes at https://github.com/conveyal/r5/pull/742/files#diff-83e437d4971e9b878b6eb7894bdf71f1d521f9d91e8b553094c9b0529f4c4400L213 it's not quite the case that this id was at `task.scenarioId` before the PR and at `task.scenario.id` after the PR. Before the PR, the scenarioId was assigned to _both_ of these fields in a single compound assignment statement, and after the PR it's only assigned to `task.scenario.id`. This explains why we can find it at the top level of the RegionalTask in old database entries, but I was then concerned that since the PR left this top-level field null, we might be verbosely sending full scenarios to every worker rather than just IDs.

This is not the case though. In Broker#enqueueTasksForRegionalJob we create a "template task" that is a slightly altered clone of the original RegionalTask. In the template task the scenario is nulled out and scenarioId is set in its place. This template task (with scenarioId) is used when distributing tasks to workers, and the original RegionalTask (with full embedded scenario) is saved in the database.

The Javadoc on the scenarioId field states that only one of scenarioId or scenario should be non-null, and the new code in the PR follows this suggestion by only setting the scenario and not the ID. However, this Javadoc was written from the perspective of using this class for broker-worker communication (not thinking of database storage or processing within the worker). In fact, both fields were set in the database entries, and upon reception by the worker the scenarioId did and still does cause the scenario field to be set, leaving both fields set.

I will update the Javadoc so this does not appear as an either-or rule, and simply describe the effect (when communicating with workers, scenarioId will override and obviate the need for scenario). 

This also suggests an alternative fix: we could simply set both fields (like we used to) when creating the RegionalTasks added to the database, allowing the scenarioId to be fetched at the top level of the RegionalTask. The database migration would then be to simply copy the scenario.id up to the scenarioId field in the parent RegionalTask on the few entries created since the release.

**Comment by abyrd** [comment]
Hmm, on second thought wasn't the point of allowing people to download the scenario JSON that we could stop nesting full serialized scenarios in the RegionalAnalysis table of the database? Shouldn't we be nulling out the scenario field when we put it in the database, such that `request.scenario.id` wouldn't even exist, in which case we want to continue using `request.scenarioId` to allow people to retrieve the scenario JSON from a file?

**Comment by abyrd** [comment]
While working on #769 I ran into another related problem. If we add something to the R5 tasks (in this case, a "failure mode" enum field) when we run a regional analysis that value is serialized into the database, nested in the regional analysis document. If this field is experimental or for internal testing use, or even a public feature that's still under development, the names of fields or enum values may change. There are some endpoints that fetch and deserialize the regional analysis documents from the database (actually mapping them into Java objects) and these will fail when the nested scenarios don't match the class definitions.

We have long been careful to ensure backward compatibility - that requests generated by the current backend can mostly be deserialized by previous workers. But this adds an additional requirement that requests generated by past backends can be deserialized by current backends (and by extension current workers). This means the request can never be pared down (have fields or enum values removed) - it can only expand forever, which is problematic long term.

First: this is another point in favor of leaving these nested scenarios out of the database and considering them archival data to be fetched as files in rare circumstances (recreating old analyses).

Second: we should reconsider how these endpoints that deserialize objects from the database work. They seem to routinely pass around whole serialized scenarios over the HTTP API. These can be very big, containing large numbers of trip IDs for example. In most (almost all?) situations we don't really need this expanded scenario JSON - a scenario ID or list of modification IDs is sufficient, or we may not need the information at all. Besides bandwidth considerations, we are spending a certain amount of resources on mapping these into Java objects, re-mapping them back to JSON, and perhaps re-mapping those back into object graphs on the JS UI side. The example I was looking at when investigating the problem described above is `RegionalAnalysisController#getRunningAnalyses`, where in order to get a list of currently running analyses, we fetch every regional analysis that has ever been run on the region, materializing them all into Java objects before selecting those that are currently running. This is done on each polling operation so the resource consumption is regular and recurring, not one-off.

**Comment by abyrd** [comment]
Tentative strategy as of our most recent meeting: we'll first apply the minimal patch (go back to using regionalAnalysis.request.scenarioId in the download endpoint, minimal migration of database to copy regionalAnalysis.request.scenario.id to regionalAnalysis.request.scenarioId). This gives us a rollback checkpoint, and we can explore a more complete solution on top of this in a branch. 

The more complete solution would probably involve removing the nested requests from the regional analysis table, moving them into a separate table or files where they'd be treated as "historical" opaque JSON that would only be displayed and not interpreted/deserialized. We'd then need a new top-level field regionalAnalysis.scenarioVersionId (or potentially scenario.scenarioVersionId if there's some scenario-versions table) distinct from regionalAnalysis.scenarioId (holding the bundle+modification hash string) that would be used to look up the specific version of the scenario used in the analysis.

**Comment by trevorgerhardt** [comment]
We should also consider re-aligning naming of the request and task. We set `RegionalAnalysis#request` to be the `RegionalTask`, but the `RegionalTask` is not the same as the `AnalysisRequest`.

**Comment by trevorgerhardt** [comment]
Fixed in #772 & https://github.com/conveyal/ui/pull/1680
