### ISSUE TITLE
Requirement of `calendar.txt`

### ISSUE THREAD

**Issue by RicoFio** [conveyal/r5#777]
Hi there,

First of all, thanks a lot to all the developers at Conveyal! R5 is an amazing concept!

While I was deploying a development environment locally on my machine, I noticed during test data ingestion that the API requires a `calendar.txt` file to be present in the uploaded `gtfs.zip`. [Here](https://transfer.sh/9RGFvW/gvb-gtfs-20210528-filtered-GVB.zip) the GTFS feed from the [original feed](https://transitfeeds.com/p/ov/814) which I then filtered by agency (GVB) using transitland's CLI and also re-validated using the same CLI.

![image](https://user-images.githubusercontent.com/3929674/148992148-a1eb13b4-fbdc-42a0-8c7c-1ebe82bb50df.png)

However, according to the [specifications](https://gtfs.org/reference/static#calendar_datestxt) `calendar.txt` and/*or* `calendar_dates.txt` can be present (both are valid gtfs feeds):

> Alternate: Omit calendar.txt, and specify each date of service in calendar_dates.txt. This allows for considerable service variation and accommodates service without normal weekly schedules. In this case service_id is an ID.

So I was wondering whether this is a bug or whether there is a rationale behind it?

Cheers,
Riccardo

**Comment by abyrd** [comment]
Hi @RicoFio, this is due to a limitation in our GTFS importer. Each file must be defined as required or non-required. Calendar is the one special case where at least one of calendar or calendar-dates must be present. We'd either have to change the mechanism or mark both these files non-required and add a separate validation module to check that at least one of them was present. These changes really should be made, but the problem was not as visible in the past until we created a better display for these error messages.

For now we have made missing table errors yellow "warnings" instead of hard failures, so you can still use the feed when the file is missing. In the long term this validation should be changed.

**Comment by abyrd** [comment]
Hi @RicoFio, we have a pull request lined up that should make these errors/warnings on the feeds more meaningful.

**Comment by abyrd** [comment]
In `com.conveyal.gtfs.loader.Table`, `CALENDAR` and `CALENDAR_DATES` are now marked as optional.   The method `com.conveyal.gtfs.validator.PostLoadValidator#validateCalendarServices` now checks once the feed is loaded to make sure some services were defined, independent of which file they came from.
