### ISSUE TITLE
Move transport network visualizer client into R5 repo

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#8]
The JS client for the TransportNetworkVisualizer web service is still over in the OTP repo at
https://github.com/opentripplanner/OpenTripPlanner/blob/master/src/main/resources/org/opentripplanner/transit/TransitNetworkVisualizer/index.html

We should move it to the R5 repo and change paths accordingly.

**Comment by buma** [comment]
There is also an option to use Mapbox GL to draw visualizer.
[Here](https://gist.github.com/buma/9408a1dc6a42141478d1) is an example.

To run it you need my [transitNetworkUI](https://github.com/buma/OpenTripPlanner-Maribor/tree/transitNetworkUI) branch since it adds permission tags to visualizer output.

It still uses raster map as a background, but geojson is drawn with the help of WebGL which makes it much faster, but we still retain the option of clicking on ways to show popups. With little JS you can also style specific paths differently since all the drawing is happening client side anyway. There is also no need to use Mapbox API key, since map is raster and can be used without it and geojson is from OTP and doesn't need it.

The only problem I found is that I can't render labels for some reason. And to style street with different permissions differently you need one layer for each color. (In carto css you could use `color: {color}` and it used color from data itself. Mapbox GL styles doesn't support that yet.

**Comment by buma** [comment]
I added mentioned visualizer into repository in jsonConfig branch. You need to start TransportVisualizer for not. But I'm working on adding it to PointToPointRouting server.

Currently it only shows permissions.
