### ISSUE TITLE
Use primitive time field rather than instant in StreetRouter.State

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#86]
All those instants in every state are a lot of indirection.

**Comment by buma** [comment]
This was used to ease debugging a little during programming because times were shown in ISO8061 in variable view instead of milliseconds of UNIX time. I implemented it in a way that outside of function only longs are seen and instant is used only inside.

But I think this can be closed now since time field seems to be primitive now.

**Comment by abyrd** [comment]
I can see the usefulness in debugging, but in R5 as a rule we want to avoid indirection in heavily used classes, just as a basic design principle. As you say, this appears to have been fixed now.

**Comment by mattwigway** [comment]
Yes, I made that change as part of the refactoring last week. If it's
helpful for debugging, I'd recommend adding a toInstant method to state and
you can put a watch on it. It would also make sense to log state times in
state.dump() as iso8601.

On Mon, Feb 29, 2016 at 1:43 AM, Marko Burjek <notifications@github.com>
wrote:

> Closed #86 <https://github.com/conveyal/r5/issues/86>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/r5/issues/86#event-570544723>.
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC
