### ISSUE TITLE
r5 analysis problem

### ISSUE THREAD

**Issue by changtung** [conveyal/r5#888]
When i do analysis i receive in server such error: 
`r5          | 18:25:45.492 [qtp583708639-24] ERROR c.c.a.c.eventbus.ErrorLogger - User local of local: com.conveyal.analysis.AnalysisServerException: org.apache.commons.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. Stream ended unexpectedly
r5          | 	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:351)
r5          | 	at org.apache.commons.fileupload.FileUploadBase.parseParameterMap(FileUploadBase.java:391)
r5          | 	at org.apache.commons.fileupload.servlet.ServletFileUpload.parseParameterMap(ServletFileUpload.java:133)
r5          | 	at com.conveyal.analysis.util.HttpUtils.getRequestFiles(HttpUtils.java:25)
r5          | 	at com.conveyal.analysis.controllers.BundleController.create(BundleController.java:107)
r5          | 	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
r5          | 	at spark.http.matching.Routes.execute(Routes.java:61)
r5          | 	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
r5          | 	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
r5          | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
r5          | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
r5          | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
r5          | 	at org.eclipse.jetty.server.Server.handle(Server.java:530)
r5          | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
r5          | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
r5          | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
r5          | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
r5          | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
r5          | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
r5          | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
r5          | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
r5          | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
r5          | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
r5          | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
r5          | 	at java.base/java.lang.Thread.run(Thread.java:829)
r5          | Caused by: org.apache.commons.fileupload.MultipartStream$MalformedStreamException: Stream ended unexpectedly
r5          | 	at org.apache.commons.fileupload.MultipartStream$ItemInputStream.makeAvailable(MultipartStream.java:1005)
r5          | 	at org.apache.commons.fileupload.MultipartStream$ItemInputStream.read(MultipartStream.java:903)
r5          | 	at java.base/java.io.InputStream.read(InputStream.java:205)
r5          | 	at org.apache.commons.fileupload.util.Streams.copy(Streams.java:100)
r5          | 	at org.apache.commons.fileupload.util.Streams.copy(Streams.java:70)
r5          | 	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:347)
r5          | 	... 24 more
r5          | 
`

**Comment by abyrd** [comment]
Hi @changtung, Conveyal has created R5 as a component of our cloud hosted transportation analysis system. This component is open source to ensure transparency in our methods and reproducibility of results in public planning processes, but we don't typically provide support for third-party deployments of the software. We do of course appreciate bug reports or suggestions and patches.

At first glance it looks like rather than calling into the core routing and accessibility computation functionality, you are using some supporting HTTP API functionality intended for our cloud-based deployment. There are many things that could be misconfigured here, and it would be hard to diagnose the problem without knowing all the details of your deployment.

If you'd like to use our cloud-hosted Conveyal tools in a professional or commercial context, feel free to contact us by email (via conveyal.com) to see if we can meet your needs. If you're working in an educational, research, or advocacy context, we can often provide discounted or even free access.
