### ISSUE TITLE
Store angles for each edge

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#90]
We should store the angles at the beginning and end of each edge rather than computing them in TurnCostCalculator. We can use binary radians (byte-scaled radians) and take advantage of overflow for circular math.

**Comment by buma** [comment]
In OTP angles are also saved as binary radians as clockwise from South but there are [TODO comments](https://github.com/opentripplanner/OpenTripPlanner/blob/master/src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java#L149) to change it to clockwise from North. Would we use clockwise from North or clockwise from South? Is any version even better?

Angles from OTP are the same as are currently used in OTP when calculating Turns (LEFT, RIGHT etc.) in Turn instructions. But are completely different 18.5° vs 54.7° as angles in turns calculated in Turn costs calculator. Probably because TurnCost calculator uses counterclockwise angle. I prefer code in Turn cost calculator since it looks nicer but I'm not sure if angles are wrong or just calculated from different direction.

**Comment by abyrd** [comment]
I don't remember why they're clockwise from South. Headings in navigation are always given as clockwise from North, making it very confusing to work with numbers referenced to South. If you adapt anything to use the code from the turn cost calculator because it's cleaner or more readable, see if you can nonetheless use standard clockwise angles.

**Comment by mattwigway** [comment]
Yeah it should definitely be clockwise from North. I have no idea why turn cost calculator is using counterclockwise from north.

**Comment by buma** [comment]
If I add this to TurnCost angle it seems that angles are clockwise from North:
```java
angle = angle < 0? angle+2*Math.PI: angle;
//360-angle-90
angle=2*Math.PI-angle-Math.PI/2;

```
Since angles seems to be counterclockwise from x which is parallel to equator.
I'll need to find a better solution since this just seems wrong

**Comment by abyrd** [comment]
Oh. Counterclockwise from the X axis is the usual convention in polar coordinates.

**Comment by buma** [comment]
Seems that OTP calculates angles as clockwise from North but saves them as clockwise from South in binary radians.
