### ISSUE TITLE
remove-trips modification

### ISSUE THREAD

**Issue by mattwigway** [conveyal/r5#95]
Here is the modification to remove trips:

```
{
  "name": "Remove short turns",
  // feed ID
  "feed": "kcata",
  // routes to remove (ignored if trips is not null)
  "routes": ["129"],
  // trips to remove
  "trips": [
    "4665093",
    "4665092",
    "4665089",
    "4665094",
    "4665096",
    "4665113",
    "4665079",
    "4665129",
    "4665118",
    "4665090",
    "4665116"
  ],
  "type": "remove-trips"
}
```

**Comment by abyrd** [comment]
This applies to all the modification types, but I'll raise it here. Should we feed-scope each ID or each modification? We could drop the "feed" property and then have a trips list like:

```
"trips": [
    "kcata:4665093",
    "kcata:4665092",
    "kcata:4665089"
  ]
```

**Comment by mattwigway** [comment]
This creates escaping issues, because it is legal to have colons in both
feed and trip ids.

**Comment by abyrd** [comment]
I think my proposal for feed ids in GTFS disallowed colons in feed ids for exactly this reason. If they are disallowed in the feed id then it doesn't hurt if they appear in the second field, it is just discouraged for legibility.

**Comment by mattwigway** [comment]
Ah. True. In that case either way is fine. I'm going to continue
representing it as a separate field in the editor because it has to be
chosen before any trips are chosen, but I could easily reformat on export.

**Comment by abyrd** [comment]
Even on the UI side, isn't this letting the implementation details leak through to the user? If someone wants to remove 4 lines, should they need to think about which feeds those lines are in to remove them, and create several delete modifications if their routes happen to come from different feeds?

It seems to me like the feed ID should be an optional criterion when for searching for routes. It helps you narrow down the list but 

Imagine the situation where (in the future) routes can be selected on the map by clicking a stop or drag-selecting a rectangle. It will be strange and inexplicable to the user if the operation fails because the selected routes come from different feeds.

**Comment by mattwigway** [comment]
As the UI is currently implemented a remove trips modification can only affect one route. But yes, I think we should feed-ID-scope all IDs, since colons are disallowed in feed IDs.
